## IRIS DATA SET PRACTICE

**What is this practice session about?**
This session of practice is to learn the basic concept of scikit-learn package

**Data Set:** Iris data set
- contains 50 samples of 3 species(setosa,verginica & Versicolor)
- measurements: Sepal length, sepal width, petal length and petal width


used: https://www.youtube.com/watch?v=hd1W4CyPX58&index=3&list=PL5-da3qGB5ICeMbQuqbbCOQWcS6OYBr5A


In [1]:
#import Iris data from Scikit-learn

from sklearn.datasets import load_iris

In [2]:
# load into variable iris variable

iris=load_iris()
type(iris)

sklearn.datasets.base.Bunch

In [3]:
print(iris.data)

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]
 [ 5.4  3.9  1.7  0.4]
 [ 4.6  3.4  1.4  0.3]
 [ 5.   3.4  1.5  0.2]
 [ 4.4  2.9  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.4  3.7  1.5  0.2]
 [ 4.8  3.4  1.6  0.2]
 [ 4.8  3.   1.4  0.1]
 [ 4.3  3.   1.1  0.1]
 [ 5.8  4.   1.2  0.2]
 [ 5.7  4.4  1.5  0.4]
 [ 5.4  3.9  1.3  0.4]
 [ 5.1  3.5  1.4  0.3]
 [ 5.7  3.8  1.7  0.3]
 [ 5.1  3.8  1.5  0.3]
 [ 5.4  3.4  1.7  0.2]
 [ 5.1  3.7  1.5  0.4]
 [ 4.6  3.6  1.   0.2]
 [ 5.1  3.3  1.7  0.5]
 [ 4.8  3.4  1.9  0.2]
 [ 5.   3.   1.6  0.2]
 [ 5.   3.4  1.6  0.4]
 [ 5.2  3.5  1.5  0.2]
 [ 5.2  3.4  1.4  0.2]
 [ 4.7  3.2  1.6  0.2]
 [ 4.8  3.1  1.6  0.2]
 [ 5.4  3.4  1.5  0.4]
 [ 5.2  4.1  1.5  0.1]
 [ 5.5  4.2  1.4  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 5.   3.2  1.2  0.2]
 [ 5.5  3.5  1.3  0.2]
 [ 4.9  3.1  1.5  0.1]
 [ 4.4  3.   1.3  0.2]
 [ 5.1  3.4  1.5  0.2]
 [ 5.   3.5  1.3  0.3]
 [ 4.5  2.3  1.3  0.3]
 [ 4.4  3.2  1.3  0.2]
 [ 5.   3.5

## Machine learning Terminalogy

- Each row is called as **Observation**
- Each column us called as **Feature**

In [4]:
print(iris.feature_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [5]:
print(iris.target)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [6]:
print(iris.target_names)

['setosa' 'versicolor' 'virginica']


- Each value we are predecting  is the **Response**(also known as target,outcome,label,dependent variable)
- Classification is Supervised learning in which response is categorical
- Regression is Supervised learning in which response is ordered and continuous

# Requirement for working with data in SciKitlearn 

- Feature & Response are separete objects
- Feature & Response should be numeric data
- Feature & Response should be Numpy Array
- Feature & Response should have specific Shape

In [73]:
#check type of feature and response
print(type(iris.data))
print(type(iris.target))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [75]:
#check the shape of the iris feature(first dimension= no. of observations, second dimension=)
print(iris.data.shape)

(150, 4)


In [9]:
#check the shape of iris data observation
print(iris.target.shape)

(150,)


In [10]:
#Store feature in matrix "x"

x=iris.data

#Store response in vector "y"
y=iris.target

### Scikit-learn 4 steps modeling pattern

**Step 1:**  Import the class you want to use


In [13]:
from sklearn.neighbors import KNeighborsClassifier

**Step 2:**  "Instantiate" the "Estimator"
 
- Estimataor is the ML word for Model
- Instantiate is the word to "create an instance of"

for more detail knn see: http://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KNeighborsClassifier.html

In [15]:
knn = KNeighborsClassifier(n_neighbors=1)
#n_neighbor is tuning parameter

- Name of the object doesnt matter
- Can specify tuning parameters
- All parameters specified are set to thier defaults

In [19]:
print(knn)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')


**Step 3:** Fit the Model with data(Model Training)

- Model is learning the relationship between x and y
- Occurs in place


In [17]:
knn.fit(x,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=1, p=2,
           weights='uniform')

**Step 4:** Predict the response for new observations

- New observations are called as "out of Sample data"
- Uses the information it learned during **Model training** process


In [18]:
knn.predict([3,4,5,6])

C:\Users\tin2941\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


array([2])

- Returns Ndarray 
- Can predict multiple observation at once

In [29]:
X_new=[[3,4,5,2],[5,4,3,2]]
knn.predict(X_new)

array([2, 1])

   ##### With different K value

In [71]:
knn1=KNeighborsClassifier(n_neighbors=5)
knn1.fit(x,y)
knn1.predict(X_new)

array([1, 1])

## Using different Classification Model

- Using **Logistic Regression**

In [72]:
from sklearn.linear_model import LogisticRegression

logreg= LogisticRegression()

logreg.fit(x,y)

logreg.predict(X_new)


array([2, 0])